server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: pc_admin
    password: root
  jpa:
    show-sql: true
liquibase:
  change-log: classpath:/db/changelog/db.changelog.xml
  default-schema: app
---
spring:
  profiles: test
  datasource:
      url: jdbc:h2:mem:test;MODE=PostgreSQL;MV_STORE=FALSE;MVCC=FALSE
      username: pc_admin
