server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: pc_admin
  jpa:
    show-sql: true

liquibase:
  change-log: classpath:/db/changelog/db.changelog.xml
  default-schema: app
